### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by pengweiweiwei** [hlsheng1/CT3D#1]
您好，请问代码什么时候可以开源呢？做毕设想参考一下，非常感谢！救救孩子吧！

**Comment by hlsheng1** [comment]
Soon after the AAAI deadline. =.=

**Comment by pengweiweiwei** [comment]
请问为什么还没有开源鸭？AAAI deadline应该以后过了吧，求代码！！！

**Comment by hlsheng1** [comment]
Thank you for your attention to our work. The code and pre-trained model will be released within a week.

> 请问为什么还没有开源鸭？AAAI deadline应该以后过了吧，求代码！！！

Thank you for your attention to our work. The code and pre-trained model will be released within a week.

**Comment by pengweiweiwei** [comment]
okkk，thanks very much ！感激涕零！

**Comment by tdzdog** [comment]
When can the code be released?

**Comment by hlsheng1** [comment]
The code and pretrained model have been released just now.

**Comment by tdzdog** [comment]
> The code and pretrained model have been released just now.

Thanks very much
