### ISSUE TITLE
Question about attention encoder

### ISSUE THREAD

**Issue by Tu1016** [hlsheng1/CT3D#11]
Hi, thanks for your brilliant work first! And I have a question about attention encoder layer. When the number of points in one box is less than 256, some vectors full of zero are used to pad the feature. Are these zero vectors participate the attention calculation when the feature pass the encoder layer? Do they have some influence?

**Comment by hlsheng1** [comment]
Yes, I have tried adding a "mask" to remove the influence of these 0 values, but the result is worse than not removing the 0 values. So, these zeros participate the attention calculation in my experiments.
