### ISSUE TITLE
Question about point selection

### ISSUE THREAD

**Issue by Eaphan** [hlsheng1/CT3D#12]
![image](https://user-images.githubusercontent.com/21019429/170445020-aa4a3f27-7338-4fdf-870e-1ec2158459e2.png)

Thanks for your impressive work. In the roi_head of CT3D, you select points by horizontal limit. Why don't you limit the height of points in the vertical direction?

**Comment by hlsheng1** [comment]
Yeah, I have tried several parameters that limit the height, and their performance have no big difference. By the way, if you visualize the point cloud of an outdoor scene, you will find that the vertical range is not necessary to limit.

**Comment by Eaphan** [comment]
Thanks for your reply. I got the point.
