### ISSUE TITLE
how to get different distance and bev metrics for waymo?

### ISSUE THREAD

**Issue by xxlbigbrother** [hlsheng1/CT3D#13]
Hi, good job!  and i want to know about how to create a pred.bin for waymo in Openpcdet! Could you share about how to create?Thanks!

**Comment by hlsheng1** [comment]
Hi, thanks for your appreciation. If you want get all the evaluation results, just change the Line 84/95 in waymo_eval.py by loading a pertained model.

**Comment by xxlbigbrother** [comment]
I have got the result. Thanks!
