### ISSUE TITLE
About Waymo evaluation

### ISSUE THREAD

**Issue by quotation2520** [hlsheng1/CT3D#16]
Hi, thank you for sharing the code!

I have a question about your experiment configuration on the Waymo dataset.
In the [waymo_dataset.yaml](https://github.com/hlsheng1/CT3D/blob/master/tools/cfgs/dataset_configs/waymo_dataset.yaml), I found that the sampling interval for 'train' and 'test' is set to 5.

```
SAMPLED_INTERVAL: {
    'train': 5,
    'test': 5
}
```

What I understand is that you've used only 20% of the training and test data for your Waymo experiments.
But the paper says that you used all validation sequences (Table 5), and I was not able to find any mention of using 20% of the training data either. 
Did you use a different configuration for your experiments? 
Thank you for clarifying!

**Comment by hlsheng1** [comment]
Hi, this is for quick trianing and validation that copied from the previous OPenPCDet codebase. In our experiemnts, we set the both the SAMPLED_INTERVAL as 1.
