### ISSUE TITLE
Differences between only car and 3classes training?

### ISSUE THREAD

**Issue by tdzdog** [hlsheng1/CT3D#3]
I notice that you only train the 'car' class in the provided config file. Is there any difference between training with all 3 classes and only the 'car' class? Can I use the provided codes for 3 classes training?

**Comment by colian** [comment]
CT3D is fine for multi classes training with slight modification (e.g., training epochs, score thresh). We will release the configuration and pretrained model for multi classes training in few days.

**Comment by hlsheng1** [comment]
CT3D is fine for multi classes training with slight modification (e.g., training epochs, score thresh). We will release the configuration and pretrained model for multi classes training in few days.

**Comment by hlsheng1** [comment]
The multi-class configuration and pretrained model have been uploaded. You can reproduce the results with the default settings.
