### ISSUE TITLE
There seems to be something error in  second_ct3d_3cat.yaml?

### ISSUE THREAD

**Issue by kx-Z** [hlsheng1/CT3D#7]
Missing num_points in transformer module.
Why num_classes=1 and what is num_dir_cls?

**Comment by hlsheng1** [comment]
Hi, thank you for pointing out these issues. "num_classes=1" means we only output the confidence instead of the real classification. Anyway, both "num_classes=1 " and "num_dir_cls" are the bugs of our previous version. We will fix these bugs today.

**Comment by kx-Z** [comment]
Thank you for your reply. I trained the model with second_ct3d.yaml，when I use 1 gpu，it takes up 12.5g of memory，but when I use 2 gpus，why is there not enough memory，my machine has a total of 33.6g of memory.I used spconv2.0.

**Comment by kx-Z** [comment]
I reduced num_workers,that's working!

**Comment by hlsheng1** [comment]
Close this issue since there is no other problem.
