### ISSUE TITLE
Imcompatible spconv versions

### ISSUE THREAD

**Issue by Co1lin** [hlsheng1/CT3D#9]
This repo doesn't specify the version of `spconv`. I installed the latest `spconv`, and got this error when running `python -m pcdet.datasets.kitti.kitti_dataset create_kitti_infos tools/cfgs/dataset_configs/kitti_dataset.yaml`:

```
File "CT3D/pcdet/datasets/processor/data_processor.py", line 51, in transform_points_to_voxels
    voxel_generator = VoxelGenerator(
TypeError: __init__() missing 1 required positional argument: 'num_point_features'
```

I find that `spconv` has deprecated `VoxelGenerator` in the newest version. Instead, they use `spconv.pytorch.utils.PointToVoxel` now. The parameters needed for `PointToVoxel` are different from `VoxelGenerator`, so it's not easy to refactor all `VoxelGenerator`. I want to know that what version of `spconv` do you use to run the code? Thank you.

**Comment by hlsheng1** [comment]
@Co1lin Sry for late, we notice that there is a lot of differences between "1.x" and "2.x" of spconv, and we use "1.2.1" version in our code.

**Comment by Co1lin** [comment]
Thanks.
